- .changeset/great-hounds-applaud.md
- packages/core/package.json
This PR fixes the exports type fields [as recommended by TypeScript](https://publint.dev/rules#export_types_invalid_format) and includes a `files` field of the files to be published.
> Fix `@lunariajs/core` .cjs types & published files

- .changeset/quick-books-exercise.md
- examples/vitepress/scripts/translation-status.ts
- examples/vitepress/ui/pt/nav.json
- examples/vitepress/ui/pt/ui.cjs
- examples/vitepress/ui/pt/ui.js
- examples/vitepress/ui/pt/ui.mjs
- examples/vitepress/ui/pt/ui.mts
- examples/vitepress/ui/pt/ui.ts
- packages/core/package.json
- packages/core/src/dashboard/components.ts
- packages/core/src/tracker.ts
- packages/core/src/types.ts
- packages/core/src/utils/config.ts
- pnpm-lock.yaml
This PR makes several improvements to UI Dictionaries and as usual, dashboard fixes:
- A new way to import UI Dictionaries, `unjs/jiti` handles the transpilation of JavaScript and TypeScript at runtime and avoids the need to use `ts-node` or other projects to run it, while JSON dictionaries are read from the file system and parsed to avoid usage of experimental Node features.
- UI Dictionaries now are 100% recursive Records, being parsed by `zod`. If a invalid UI Dictionary format is found, the code throws an error and exits.
- This new approach removes the support for different specified modules, therefore its option is now deprecated and removed from the config file.
- Solved a bug where the `<StatusByContent />` table component would render the status in the wrong order.
> UI Dictionaries improvements & dashboard fixes

- .changeset/tender-deers-taste.md
- packages/core/package.json
- packages/core/src/dashboard/components.ts
- packages/core/src/schemas/config.ts
- packages/core/src/schemas/dashboard.ts
- packages/core/src/schemas/misc.ts
- packages/core/src/tracker.ts
- packages/core/src/types.ts
- packages/core/src/utils/git.ts
- packages/core/src/utils/misc.ts
- pnpm-lock.yaml
This PR is focused on improving the links generated from the dashboard. Now, we have a new configuration option called `localePathConstructor`, meant to be the inverse of `sharedPathResolver`, that is, it creates a locale-specific path from a source file path, meaning when we don't have that page yet but we need a hypothetical one for a "Create page" link.
The dependency `ufo` was also introduced to help take care of joining and normalizing the URLs across the dashboard.;
> Add `localePathConstructor` & improve git hosting links

- .changeset/giant-apples-greet.md
- packages/core/src/tracker.ts
- packages/core/src/types.ts
- packages/core/src/utils/misc.ts
This PR improves how the` translatableProperty` system is handled. In resume, now, we're considering that if you've set `translatableProperty` but it wasn't found, it will be marked as not translatable, while if the file format does not support frontmatter, it will be marked as translatable regardless.
> Improve how `translatableProperty` is handled

- .changeset/fuzzy-badgers-do.md
- packages/core/src/utils/git.ts
Fixes a small issue where the repository would contain a trailing slash and fail to properly find the repository to clone
> Fix trailing slash issue in remote cloning

- .changeset/perfect-timers-float.md
- build.preset.ts
- package.json
- packages/core/build.config.ts
- packages/core/package.json
- packages/core/src/cli.ts
- packages/create-lunaria/README.md
- packages/create-lunaria/build.config.ts
- packages/create-lunaria/package.json
- packages/create-lunaria/src/create-lunaria.ts
- packages/create-lunaria/tsconfig.json
- pnpm-lock.yaml
This PR adds the new `create-lunaria` package, meant to help users add Lunaria to their projects. It's a very basic version that will be expanded upon when we get to have other official Lunaria packages.
> Add `create-lunaria` package and improve `@lunariajs/core` configuration error

- .changeset/good-dingos-wave.md
- packages/core/src/dashboard/components.ts
- packages/core/src/schemas/dashboard.ts
This PR adds a new `dashboard.basesToHide` option, which receives an array of path bases that should be hidden from the rendered dashboard link labels. This is to make the dashboard more pleasing when your content is several levels deep from its content.
> Add `dashboard.basesToHide` option

- .changeset/brave-spoons-join.md
- packages/core/config.schema.json
- packages/core/scripts/schema.ts
- packages/core/src/dashboard/components.ts
- packages/core/src/dashboard/utils.ts
- packages/core/src/schemas/config.ts
- packages/core/src/schemas/dashboard.ts
This PR adds a new `customCss` option to the dashboard, meaning you can add relative paths `.css` files that will be inlined and added to the final dashboard.
> Add new `customCss` dashboard option

- .changeset/fair-parrots-try.md
- packages/core/config.schema.json
- packages/core/src/schemas/config.ts
This PR changes the `ignoreKeywords` defaults to `lunaria-ignore` and `fix typo` only.
> Change `ignoreKeywords` defaults

- .changeset/ten-lions-rush.md
- packages/core/config.schema.json
- packages/core/src/schemas/locale.ts
- packages/core/src/tracker.ts
- packages/core/src/types.ts
This PR adds support for tracking only dictionary-type files. Now, you can decide between choosing a `content` and/or `dictionaries` field depending on your type of project. This will also work for future tracking systems.
> Add support for tracking only dictionaries

- .changeset/wild-turtles-admire.md
- packages/core/config.schema.json
- packages/core/src/dashboard/components.ts
- packages/core/src/dashboard/utils.ts
- packages/core/src/schemas/dashboard.ts
This PR adds support for adding a favicon into your dashboard, be it through an `external` link or by inlining (`inline`) an SVG in the repository's file system. You can use both to have a fallback and preferred icon as well.
> Add favicon support

- packages/core/config.schema.json
- packages/core/src/schemas/dashboard.ts
This PR adds the missing Zod descriptions to the `favicon` configuration object.
> Add missing favicon descriptions

- .changeset/beige-suns-work.md
- packages/core/config.schema.json
- packages/core/src/schemas/config.ts
- packages/core/src/tracker.ts
- packages/core/src/utils/misc.ts
This PR fixes issues that were happening with `rootDir`, now the URL follows the expected format and the default value reflects this.
> Fix `rootDir` issues

- .changeset/khaki-hairs-hear.md
- packages/core/config.schema.json
- packages/core/src/dashboard/components.ts
- packages/core/src/schemas/dashboard.ts
This PR wraps most UI labels used into a `unsafeStatic()` to allow users to insert HTML and entities into it when necessary. Given the nature of these strings to be static and from the user's config, that should not be a security concern.
> Allow user labels to include HTML

- docs/src/content/docs/manual-installation.mdx
Fixed the path in `content.location` for Portuguese locale.
> Fix typo in manual-installation.mdx

- .changeset/brown-pianos-flow.md
- packages/create-lunaria/src/create-lunaria.ts
Within the "Next steps" of the setup wizard, `pnpm` is being displayed regardless of the type of package manager being used. Fixed to show `packageManager.name` instead.
> Display `packageManager.name` instead of hardcoding `pnpm`

- .changeset/silver-trees-poke.md
- packages/core/package.json
- packages/core/src/dashboard/components.ts
- pnpm-lock.yaml
This PR fixes the indentation of inlined styles by using `redent` to remove redundant indentation and indent properly after.
> Fix inline styles indentation

- .changeset/ten-papayas-mix.md
- packages/core/config.schema.json
- packages/core/src/dashboard/components.ts
- packages/core/src/schemas/dashboard.ts
This PR improves the `external` favicon API to allow for multiple external favicons.
> Allow multiple `external` favicons

- .changeset/quiet-starfishes-beg.md
- docs/src/content/docs/manual-installation.mdx
- packages/core/config.schema.json
- packages/core/src/cli.ts
- packages/core/src/schemas/config.ts
This PR updates the default `outDir` and `cloneDir` values to now be centralized in `dist/lunaria/*`.
> Update output defaults

- .changeset/lucky-cycles-sparkle.md
- examples/nextra/lunaria.config.json
- packages/core/src/tracker.ts
This PR improves the new content source API by changing the `@path` variable to a better pattern that better supports the conventional directory-based i18n. This does come with the need to use a custom `:path` for more specific strategies, e.g. Nextra's.
I've also added the `@locales` variables to give you an joined version of all the locales in case you also need to create a custom `:lang`.
> Improve content API variables

- .changeset/good-dogs-swim.md
- packages/core/src/dashboard/components.ts
- packages/core/src/dashboard/styles.ts
This PR fixes the styling of dictionary entries that were being styled by mistake as the progress bar details.
> Fix styling of dictionary entries

- .changeset/stale-guests-kick.md
- packages/core/package.json
- packages/core/src/config/schemas.ts
- packages/core/src/dashboard/components.ts
- packages/core/src/dashboard/index.ts
- packages/core/src/dashboard/styles.ts
- packages/core/src/index.ts
- packages/core/src/types.ts
- pnpm-lock.yaml
This PR simplifies the component system by providing our own `html`, without Lit. Also, this makes our dashboard not be formatted or escaped/sanitized by default. Since Lunaria is 'static, users are expected not to include user-provided content, and if they do, to escape/sanitize on their end.
This also increasingly reduces the final install/bundle size of using `@lunariajs/core`.
> Simplify component system and dashboard generation

- .changeset/dirty-pandas-know.md
- packages/core/config.schema.json
- packages/core/src/config/schemas.ts
This changes the `cloneDir` default to the `node_modules/.cache/lunaria/history`, which will avoid accidentally deploying the entire history by default.
> Change `cloneDir` default

- .changeset/fresh-peas-pay.md
- packages/core/src/config/schemas.ts
This PR improves the renderer config's component types by adding the specified arguments using `z.custom()`. When using `z.function().args()` we get an exponential increase in bundle size, since the config schema will copied over each single time. This is unfortunate, but my main reason to introduce this was to add editor hints, instead of validating the arguments used.
> Improve renderer components types

- .changeset/yellow-worms-prove.md
- packages/core/src/status/git.ts
- packages/core/src/status/index.ts
This PR improves the `gitHostingLinks.history()` by making `sinceDate` optional and not including the `since` query param if not passed.
> Improve generated `gitHostingLinks.history()`

- .changeset/unlucky-pens-juggle.md
- packages/core/src/status/index.ts
This PR updates the Tracker Directives names for more idiomatic ones, namely `@lunaria-track` and `@lunaria-ignore`. Note that `@tracker-major` and `@tracker-minor` are still valid, but will be deprecated in a future release.
> Update tracker directive names

- .changeset/brave-bats-wink.md
- packages/core/src/cli/sync/index.ts
- packages/core/src/config/index.ts
This PR adds a new `readConfig` function to read the raw config when you want to read its JSON without any validation, generally to then write it back, like in the `sync` command or integrations such as `@lunariajs/starlight`. This also fixes an issue with `writeConfig` that would throw an invalid extension error, even when it's valid.
> Add `readConfig` and fix `writeConfig` issue

- .changeset/rotten-carpets-explode.md
- packages/core/src/status/git.ts
This PR exposes the `simpleGit` instance used for integrations to use, while also improving the error when it tries to find the commits for an empty git repo.
> Expose `simpleGit` instance and improve error

- packages/core/package.json
This PR removes `CHANGELOG.md` from `@lunariajs/core`'s package installation files.
> Remove `CHANGELOG.md` from the package install

- .changeset/good-hats-drop.md
- docs/src/content/docs/getting-started.mdx
- docs/src/content/docs/manual-installation.mdx
- docs/src/content/docs/reference/cli.mdx
- packages/core/src/cli/console.ts
- packages/core/src/cli/index.ts
- packages/core/src/cli/init/index.ts
- packages/core/src/cli/sync/index.ts
- packages/core/src/cli/types.ts
This PR adds the new `lunaria init` command, meant to be used instead of `create-lunaria`, which will be deprecated soon. The documentation has also been updated to reflect this.
> Add lunaria init command

- .changeset/honest-ligers-dress.md
- docs/src/content/docs/getting-started.mdx
- docs/src/content/docs/index.mdx
- docs/src/content/docs/manual-installation.mdx
- docs/src/content/docs/reference/cli.mdx
- packages/core/package.json
- packages/core/src/cli/console.ts
- packages/core/src/cli/helpers.ts
- packages/core/src/cli/index.ts
- packages/core/src/cli/init/index.ts
- packages/core/src/cli/preview/index.ts
- packages/core/src/cli/types.ts
- pnpm-lock.yaml
This PR adds the new `lunaria preview` command, meant to start a preview server with your built dashboard from `lunaria build`.
This also adds a new `lunaria:preview` added by `lunaria init`, while updates the documentation to mention it.
> Add lunaria preview command

- .changeset/famous-bikes-carry.md
- packages/core/src/utils.ts
Fixes an type and bundling issue with `jiti` by importing it through a require, instead of a normal ESM import.
> Fix jiti type and bundling issue

- .changeset/khaki-cars-fry.md
- docs/src/content/docs/reference/cli.mdx
- packages/core/src/cli/build/index.ts
- packages/core/src/cli/helpers.ts
- packages/core/src/cli/index.ts
- packages/core/src/cli/types.ts
This PR adds a new build option to log the generated status JSON in the console. This will be used by Lunaria's GitHub Action.
> Add build option to stdout generated status

- .changeset/twenty-pants-draw.md
- examples/starlight/package.json
- packages/starlight/README.md
- packages/starlight/package.json
- packages/starlight/src/bin/lunaria.mjs
- pnpm-lock.yaml
Removes the CLI redirect from `@lunariajs/core` in `@lunariajs/starlight`. The recommendation is to have both installed as dependencies in your project, not as a subdependency.
> Remove CLI redirect

- .changeset/curvy-parrots-relax.md
- packages/core/src/status/index.ts
- packages/core/src/types.ts
Include the commit hashes in the generated `status.json` file.
This allows third-party tools to refer to the exact commits where the translation diff happened instead of relying on the timestamp of the commits increasing monotonically.
> Include commit hash in localization status data

- docs/src/content/docs/reference/renderer.mdx
- docs/src/content/docs/reference/runtime.mdx
This PR adds a basic Runtime API page on the Reference section of the docs.
> Add basic Runtime API page

- docs/src/content/docs/tools/github-action.mdx
This PR adds docs instructions for running the GitHub Action properly on monorepos.
> Add GitHub Action set up instructions for monorepo

- docs/astro.config.mjs
- docs/src/content/docs/guides/dashboard-customization.mdx
- docs/src/content/docs/manual-installation.mdx
This PR adds the new Dashboard Customization page to the docs, giving a more user-oriented overview of all the ways you can customize your dashboard.
> Add new dashboard customization page

- .changeset/early-tomatoes-reflect.md
- packages/core/src/status/index.ts
This PR fixes a regression with the `sinceDate` query parameter added to git hosting links. To be precise, the last major *source* change date was being given, while what was desired was the last *localization* major change date.
> Fix source history incorrect listing
