package.json
Adds the missing package manager key to root `package.json`
=> Add package manager key to `package.json`

package.json
=> Add missing version command

.changeset/clever-adults-play.md, examples/vitepress/package.json, packages/core/CHANGELOG.md, packages/core/package.json, pnpm-lock.yaml
=> Revert "[ci] release"

.changeset/config.json
This PR fixes the release CI by marking the `access` field as `"public"`
=> Fix release CI

.changeset/great-poems-jam.md, .github/workflows/release.yml, package.json
Adds the missing `pnpm build` step during package release
=> Build packages during release

.changeset/orange-candles-bake.md, packages/core/package.json
=> Fix ESM exports

.changeset/perfect-olives-rescue.md, packages/core/src/dashboard/components.ts, packages/core/src/index.ts, packages/core/src/tracker.ts, packages/core/src/types.ts, packages/core/src/utils/config.ts, packages/core/src/utils/git.ts, tsconfig.json
A few improvements to the `tsconfig.json` file, trying to fix the TypeScript issues happening.
=> Improve `tsconfig.json` configuration

.changeset/swift-impalas-pretend.md, packages/core/src/tracker.ts
Remove an accidental `console.log` that slipped by, oops
=> Remove accidental `console.log`

.changeset/nice-schools-design.md, packages/core/src/tracker.ts
This PR fixes the logic of Tracker Directives, as the proper status wasn't being considered.
=> Fix tracker directives logic

docs/astro.config.mjs, docs/src/content/docs/index.mdx, docs/src/styles/landing.css, docs/src/styles/theme.css
Add some small changes to the Lunaria landing page
=> Add small changes to docs landing page

README.md, docs/src/content/docs/getting-started.md, docs/src/content/docs/getting-started.mdx, docs/src/content/docs/index.mdx
This PR adds a proper Getting Started page to the docs
=> Add Getting Started docs

docs/package.json, pnpm-lock.yaml
This PR updates the Lunaria Docs setup in order to use Expressive Code, added in the last minor.
=> Update Starlight for EC support

.changeset/cool-pumas-flash.md, README.md, packages/core/README.md
This PR updates both the monorepo and `@lunariajs/core` package READMEs.
=> Add new updated READMEs

.changeset/five-needles-stare.md, examples/vitepress/lunaria.config.json, packages/core/src/dashboard/components.ts, packages/core/src/schemas/config.ts, packages/core/src/tracker.ts, packages/core/src/types.ts, packages/core/src/utils/git.ts, packages/core/src/utils/misc.ts
This PR adds the new repository hosting API, adding support for not only GitHub but also GitLab. This PR also makes some refactors across the dashboard generation and the routingStrategy API
=> Add new repository hosting API

.changeset/eleven-glasses-peel.md, examples/vitepress/lunaria.config.json, packages/core/README.md, packages/core/package.json, packages/core/scripts/schema.ts, packages/create-lunaria/build.config.ts, packages/create-lunaria/src/create-lunaria.ts, pnpm-lock.yaml
This PR adds a new JSON Schema generation to the build pipeline, converting the core package's Zod configuration schema to a JSON Schema so there's Intelissense in code editors.
=> Add configuration JSON Schema support

docs/astro.config.mjs, docs/package.json, docs/src/content/docs/features/tracking.mdx, docs/src/content/docs/getting-started.mdx, docs/src/content/docs/manual-installation.mdx, docs/src/content/docs/workflow.mdx, docs/src/styles/theme.css, examples/vitepress/lunaria.config.json, pnpm-lock.yaml
This PR adds the new Manual Installation page, a few draft docs, update to Starlight v0.15 and Astro v4.0.3, and new theme colors: because yes.
=> Add partial docs work

.changeset/clever-spoons-reflect.md, packages/core/config.schema.json, packages/core/src/dashboard/components.ts, packages/core/src/dashboard/styles.ts
This PR adds the new progress bar design, meant to be more customizable and visually pleasing.
=> Add new progress bar design

.changeset/silly-grapes-move.md, packages/core/config.schema.json, packages/core/package.json, packages/core/src/dashboard/components.ts, packages/core/src/dashboard/styles.ts, packages/core/src/index.ts, packages/core/src/schemas/config.ts, packages/core/src/schemas/dashboard.ts, packages/core/src/tracker.ts, packages/core/src/types.ts, packages/core/src/utils/misc.ts, pnpm-lock.yaml
This PR improves the component rendering system by using `@lit-labs/ssr` instead of a custom function, fixing the existing issues with some of `lit-html`'s features.
=> Fix component rendering issues

.changeset/honest-eyes-give.md, packages/core/config.schema.json, packages/core/package.json, packages/core/scripts/schema.ts, packages/core/src/cli.ts, packages/core/src/schemas/config.ts, packages/core/src/schemas/dashboard.ts, packages/core/src/schemas/locale.ts, pnpm-lock.yaml
This PR improves the configuration errors and its logging, giving a comprehensive list of errors found and a new custom when multiple locales share the same `lang`.
=> Improve configuration errors

.changeset/eighty-moles-attend.md, packages/core/src/dashboard/styles.ts
This PR improves the dashboard's CSS variables to follow the `--ln-*` pattern, as well as new, more balanced, default colors.
=> Improve color schema and variables

.changeset/lucky-feet-raise.md, packages/core/src/dashboard/components.ts, packages/core/src/schemas/config.ts
This PR adds two new slot options: `afterStatusByLocale` & `afterStatusByContent`
=> Add new slot options

.changeset/thick-ladybugs-shake.md, packages/core/src/api.ts, packages/core/src/cli.ts, packages/core/src/constants.ts, packages/core/src/index.ts
This PR adds a programmatic API to use Lunaria with your own config/in other contexts.
=> Add programmatic API

.github/PULL_REQUEST_TEMPLATE.md
Added a simple template for PRs for new contributors
=> add: PR template

.changeset/moody-hounds-stare.md, docs/src/content/docs/manual-installation.mdx, examples/nextra/lunaria.config.json, examples/vitepress/lunaria.config.json, packages/core/README.md, packages/core/config.schema.json, packages/core/src/config/schemas.ts, packages/core/src/dashboard/components.ts, packages/core/src/status/dictionaries.ts, packages/core/src/status/git.ts, packages/core/src/status/index.ts, packages/core/src/types.ts
This PR improves the `LocalizationStatus` types to be more descriptive, while also changing the final resulting status schema.
=> Improve types and status signature

.changeset/slimy-chefs-sniff.md, docs/src/content/docs/reference/cli.mdx, packages/core/src/cli/build/index.ts, packages/core/src/cli/helpers.ts, packages/core/src/cli/index.ts, packages/core/src/cli/types.ts
Reverts yanthomasdev/lunaria#120
=> Revert "Add build option to stdout generated status"

.changeset/slow-worms-cross.md, packages/core/package.json, packages/core/src/config/error-map.ts, packages/core/src/config/index.ts, packages/core/src/config/schemas.ts, pnpm-lock.yaml
This PR improves our error handling with a new `parseWithFriendlyErrors` function and a proper Zod error map, dropping the dependency on `zod-validation-error`.
- Closes #
- Suggested label:
=> Improve Zod errors

docs/astro.config.mjs, docs/src/content/docs/tools/github-action.mdx
This PR adds the docs for the Lunaria GitHub Action, soon to be officially released.
=> Add GitHub Action docs

README.md, docs/astro.config.mjs, docs/src/content/docs/getting-started.mdx, docs/src/content/docs/manual-installation.mdx, docs/src/content/docs/reference/configuration.mdx, examples/nextra/lunaria.config.json, examples/starlight/lunaria.config.json, examples/vitepress/lunaria.config.json, packages/core/README.md, packages/core/config.schema.json, packages/core/package.json, packages/core/src/cli/init/index.ts, packages/core/src/config/schemas.ts, packages/starlight/package.json
Edit GitHub URL to yanthomasdev/lunaria
```diff
- Yan-Thomas/lunaria',
+ yanthomasdev/lunaria',
``` 
- Closes #
- Suggested label:
=> Conf: Edit GitHub URL to `/yanthomasdev/lunaria`

docs/astro.config.mjs, docs/package.json, docs/src/content/docs/manual-installation.mdx, docs/src/content/docs/reference/configuration.mdx, docs/src/content/docs/tools/github-action.mdx, pnpm-lock.yaml
This PR updates our Starlight documentation to its latest version, adds the `starlight-links-validator` plugin for link validation, as well as updates the GitHub Action docs with extra information.
=> Update Starlight and GitHub Action docs

.prettierignore, docs/src/content/docs/guides/dashboard-customization.mdx
This PR fixes the issue with MD/MDX files being formatted when they shouldn't.
=> Fix MD/MDX files formatting

.github/FUNDING.yml, .github/ISSUE_TEMPLATE/---01-bug-report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/dependabot.yml, .github/labeler.yml, .github/workflows/labeler.yml, README.md
This PR adds a few changes to the repository in preparation for its official beta release and announcement:
- Auto-labelling action
- Updated README with funding and package information.
- Dependabot set up
- Issue Template
=> Finish GitHub housekeeping tasks

docs/src/content/docs/blog/introducing-lunaria.md
Reorders some of the opening content
=> reorder intro paragraphs

.changeset/config.json, package.json, pnpm-lock.yaml
This PR adds GitHub support to the Changesets set up.
=> Add GitHub changeset generation
